project:
  type: website
  output-dir: docs

website:
  title: "A Guide through My Honours Thesis"
  search: true
  navbar:
    left: []
    right: []

format:
  html:
    theme: cosmo
    toc: true
    mathjax: true
    css: styles.css
